version: "2.1"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - JELLYFIN_PublishedServerUrl=https://enter.your.domain.here.com #optional
    volumes:
      - ./Media/Serien:/data/tvshows #Volume where u put ur media
      - ./Media/Filme:/data/movies #Volume where u put ur media
      - ./Media/Music:/data/music #Volume where u put ur media
      - ./Volumes/cache:/cache #Volume where jellyfin chaches ur information (if you cache on a sd card it will break faster, so I recommend outsourcing it)
      - ./Volumes/config:/config #Colfiguration files as well as metadata.
    ports:
      - 8096:8096 #I used the default port since idk what other service does use this port.
    restart: unless-stopped
